### PR TITLE
Inspect the ancestors' attribute (fix #16)

### LINKED ISSUE #16: Identify JsonRpcMethodAttribute on the interface
```c#
    public interface IManager
    {
        [JsonRpcMethod]
        public string RegisterApp(string name);
    }
    public class Manager : JsonRpcService, IManager
    {
        [JsonRpcMethod]  // I don't think this is necessary since there is a JsonRpcMethodAttribute on the interface
        public string RegisterApp(string name)
        {
            var token = "abcdefg"; //hard-coded token for test
            return token;
        }
    }
```

What I use to build a host is 
```c#
hostBuilder.Register(typeof(Manager));
```

Version: v0.5.4 (20200621)

### PR DESCRIPTION
**Pull request by ArcticLampyrid**

### CODE REVIEW

**Comment by ArcticLampyrid** [comment]
Relative API document: [Click me!](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.customattributeextensions.getcustomattribute?view=netcore-3.1#System_Reflection_CustomAttributeExtensions_GetCustomAttribute__1_System_Reflection_MemberInfo_System_Boolean_)

**Review by CXuesong — CHANGES_REQUESTED** [review]
I'm afraid your change won't work. See [this post](https://stackoverflow.com/questions/251806/attributes-on-an-interface) for possible cause. And though it's not usual but `GetCustomAttribute` overload without bool parameter actually calls the overload with bool parameter, passing true as value. Thus your PR effectively changes no runtime behavior.

**Comment by CXuesong** [comment]
Thanks for your PR! Please validate your change locally (ideally, also adding the unit test case) before proposing it.

As I'm still travelling, you may well go ahead and give it another try. Good luck!

**Comment by ArcticLampyrid** [comment]
Closed since this does not really work

**Pull request closed without merging**
